version: "3.7"
services:
  web:
    image: javalisson/github-followers:0.1
    command: nginx
    build:
      context: .
      target: production
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=production
