version: "3.7"
services:
  web:
    image: javalisson/github-followers:dev
    command: npm run serve
    build:
      context: .
      target: base
    volumes:
      # WARNING: Don't map ./ to /app because it overrides the node_modules folder
      - ./app.json:/app/app.json
      - ./babel.config.js:/app/babel.config.js
      - ./.browserslistrc:/app/.browserslistrc
      - ./docker-compose.dev.yml:/app/docker-compose.dev.yml
      - ./docker-compose.yml:/app/docker-compose.yml
      - ./Dockerfile:/app/Dockerfile
      - ./.editorconfig:/app/.editorconfig
      - ./.eslintrc.js:/app/.eslintrc.js
      - ./.git:/app/.git
      - ./.gitignore:/app/.gitignore
      - ./.netlify:/app/.netlify
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./public:/app/public
      - ./README.md:/app/README.md
      - ./src:/app/src
      - ./static.json:/app/static.json
      - ./vue.config.js:/app/vue.config.js
    ports: 
      - "8080:8080"
    environment:
      - NODE_ENV=development
